config/routes.rb
Timetable::Application.routes.draw do
  root :to => "user_sessions#new"
  get "user/new"

  
  get "events/new"

  get "events/edit"
  resources :users
  resources :events
  resources :sujits

  resources :user_sessions

  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout

  get "user_sessions/new"

  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  

  root :to => "user_sessions#new"

end

app/models/sujit.rb
class Sujit < ActiveRecord::Base
end

app/controllers/sujits_controller.rb
class SujitsController < ApplicationController
  # GET /sujits
  # GET /sujits.xml
  def index
    @sujits = Sujit.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @sujits }
    end
  end

  # GET /sujits/1
  # GET /sujits/1.xml
  def show
    @sujit = Sujit.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @sujit }
    end
  end

  # GET /sujits/new
  # GET /sujits/new.xml
  def new
    @sujit = Sujit.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @sujit }
    end
  end

  # GET /sujits/1/edit
  def edit
    @sujit = Sujit.find(params[:id])
  end

  # POST /sujits
  # POST /sujits.xml
  def create
    @sujit = Sujit.new(params[:sujit])

    respond_to do |format|
      if @sujit.save
        format.html { redirect_to(@sujit, :notice => 'Sujit was successfully created.') }
        format.xml  { render :xml => @sujit, :status => :created, :location => @sujit }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @sujit.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /sujits/1
  # PUT /sujits/1.xml
  def update
    @sujit = Sujit.find(params[:id])

    respond_to do |format|
      if @sujit.update_attributes(params[:sujit])
        format.html { redirect_to(@sujit, :notice => 'Sujit was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @sujit.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /sujits/1
  # DELETE /sujits/1.xml
  def destroy
    @sujit = Sujit.find(params[:id])
    @sujit.destroy

    respond_to do |format|
      format.html { redirect_to(sujits_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/sujits_helper.rb
module SujitsHelper
end

app/views/sujits/_form.html.erb
<%= form_for(@sujit) do |f| %>
  <% if @sujit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sujit.errors.count, "error") %> prohibited this sujit from being saved:</h2>

      <ul>
      <% @sujit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :snss %><br />
    <%= f.text_field :snss %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sujits/edit.html.erb
<h1>Editing sujit</h1>

<%= render 'form' %>

<%= link_to 'Show', @sujit %> |
<%= link_to 'Back', sujits_path %>

app/views/sujits/index.html.erb
<h1>Listing sujits</h1>

<table>
  <tr>
    <th>Snss</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sujits.each do |sujit| %>
  <tr>
    <td><%= sujit.snss %></td>
    <td><%= link_to 'Show', sujit %></td>
    <td><%= link_to 'Edit', edit_sujit_path(sujit) %></td>
    <td><%= link_to 'Destroy', sujit, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sujit', new_sujit_path %>

app/views/sujits/new.html.erb
<h1>New sujit</h1>

<%= render 'form' %>

<%= link_to 'Back', sujits_path %>

app/views/sujits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Snss:</b>
  <%= @sujit.snss %>
</p>


<%= link_to 'Edit', edit_sujit_path(@sujit) %> |
<%= link_to 'Back', sujits_path %>