config/routes.rb
Timetable::Application.routes.draw do
  root :to => "user_sessions#new"
  get "user/new"

  
  get "events/new"

  get "events/edit"
  resources :users
  resources :events
  resources :sujits

  resources :user_sessions

  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout

  get "user_sessions/new"

  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  

  root :to => "user_sessions#new"

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_event_calendar
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :require_user
   layout 'events'
  # GET /events
  # GET /events.xml
  def index
    @events = Event.paginate( :page => params[:page], :per_page => 10 , :order => 'created_at DESC')

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @events }
    end
  end

  # GET /events/1
  # GET /events/1.xml
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @event }
    end
  end

  # GET /events/new
  # GET /events/new.xml
  def new
    @event = Event.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.xml
  def create
    @event = Event.new(params[:event])
     @event[:user_id] = current_user.id
    respond_to do |format|
      if @event.save
        format.html { redirect_to(@event, :notice => 'Event was successfully created.') }
        format.xml  { render :xml => @event, :status => :created, :location => @event }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.xml
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to(@event, :notice => 'Event was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.xml
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to(events_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :details %><br />
    <%= f.text_area :details, :cols => '40' , :rows => '10' %>
  </div>
  <div class="field">
    <%= f.label :start_at %><br />
    <%= f.datetime_select :start_at , :default => Time.now.getlocal %>
  </div>
  <div class="field">
    <%= f.label :end_at %><br />
    <%= f.datetime_select :end_at , :default => Time.now %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.check_box :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %> |
<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Destroy', @event, :confirm => 'Are you sure?', :method => :delete %>

app/views/events/index.html.erb
<h1 align="center">Listing all events</h1>
<p align="center" style="color:black"><%= will_paginate(@events) %></p>
<table border="1" cellpadding="15" cellspacing="1" width="1200" > 
  <tr bgcolor="#7F0E30" style="color:white">
    <th width="10%">Name</th>
    <th width="">Details</th>
    <th width="10%">Start at</th>
    <th width="10%">End at</th>
    <th width="12%">Time Remaining</th>
    </tr>

<% @events.each do |event| %>
<% if event.status? %>
  <tr bgcolor="#CFFF6D">
<% else if event.end_at < Time.now %>
  <tr bgcolor="#FFCC99">
<% else %>
  <tr bgcolor="#69FAFF">
<% end end %>
    <td><H3 style="color:black"><%= link_to event.name, event %></H3></td>
    <td><%= event.details %></td>
    <td align="center" style=" font-size:15px;"><%= event.start_at.strftime("%d-%m-%Y %I:%M %p")   %><% Time.now %></td>
    <td align="center" style=" font-size:15px;"><%= event.end_at.strftime("%d-%m-%Y %I:%M %p") %></td>
    <td align="center">
<% if event.end_at > Time.now %> 
<%= distance_of_time_in_words( event.end_at , Time.now , include_seconds = true ) %>
<% else if event.status? %>
<%= "Time is up" %><br/>
<% else %>
<%= "Time is up" %><br/>
( <%= distance_of_time_in_words( event.end_at , Time.now , include_seconds = true ) %> )
<% end end %>
</td></tr>
<% end %>
</table>
<br/>
<%= will_paginate(@events) %>
<br />

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>


<%= link_to 'Back', events_path %> 

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @event.name %>
</p>

<p>
  <b>Details:</b>
  <%= @event.details %>
</p>

<p>
  <b>Start at:</b>
  <%= @event.start_at.getlocal %>
</p>

<p>
  <b>End at:</b>
  <%= @event.end_at.getlocal %>
</p>

<p>
  <b>Status:</b>
  <%= @event.status %>
</p>


<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %> |
<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Destroy', @event, :confirm => 'Are you sure?', :method => :delete %>