config/routes.rb
Timetable::Application.routes.draw do
  root :to => "user_sessions#new"
  get "user/new"

  
  get "events/new"

  get "events/edit"
  resources :users
  resources :events
  resources :sujits

  resources :user_sessions

  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout

  get "user_sessions/new"

  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  

  root :to => "user_sessions#new"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Timetable</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
 <div id="nav" align="center">
<% if current_user.object_id.nil? %>
<%= link_to "Login", :login %> 
<% else %>
<%= link_to "Logout", :logout %> 
<% end %>
| <%= link_to 'New Event', new_event_path %> | <%= link_to 'All Events', events_path %> |
<%= link_to 'Calendar', calendar_path %>
    </div>
<br/><br/>
<%= yield %>

</body>
</html>

app/views/layouts/events.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Timetable</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
 <div id="nav" align="center">
<% if current_user.id.nil? %>
<%= link_to "Login", :login %> 
<% else %>
<%= link_to "Logout", :logout %> 
<% end %>
| <%= link_to 'New Event', new_event_path %> | <%= link_to 'All Events', events_path %> |
<%= link_to 'Calendar', calendar_path %>
    </div>
<table align='center'><tr><td>
<%= yield %>
</td></tr></table>
</body>
</html>